"""
Utility tools for AI Browser agents.

These tools support the agent's internal reasoning process — summarizing
pages for context compression, planning next steps, and logging observations.
They don't interact with the browser or filesystem directly; instead they
help the agent think more effectively.
"""

from __future__ import annotations

from langchain_core.tools import tool

from ai_browser.utils.runtime import runtime
from ai_browser.utils.html_cleaner import HTMLCleaner

_cleaner = HTMLCleaner(remove_boilerplate=True)


@tool
async def summarize_page() -> str:
    """
    Generate a concise LLM-powered summary of the current page.

    Use this when you need a quick understanding of what a page contains
    without reading all the text. This is especially useful for deciding
    whether a page is relevant to your task before doing full extraction.

    The summary is generated by sending the cleaned page text to the LLM.

    Returns:
        A 2-4 sentence summary of the page content.
    """
    from ai_browser.config import get_llm

    page = runtime.get_page()
    html = await page.content()
    text = _cleaner.clean(html)

    # Truncate for summarization
    if len(text) > 8000:
        text = text[:8000]

    llm = get_llm()
    prompt = (
        f"Summarize the following web page content in 2-4 sentences. "
        f"Focus on what the page is about and what actions or information "
        f"are available.\n\n"
        f"URL: {page.url}\n\n"
        f"Content:\n{text}"
    )

    response = await llm.ainvoke(prompt)
    return f"Page summary ({page.url}):\n{response.content}"


@tool
def plan_next_steps(
    current_situation: str,
    goal: str,
    options: str = "",
) -> str:
    """
    Articulate your current situation and plan next steps.

    Use this tool to organize your thinking before taking action.
    This is a reasoning tool — it doesn't perform any action, but helps
    you make better decisions by forcing structured thought.

    Args:
        current_situation: Describe where you are and what you've done so far.
        goal: What you're ultimately trying to accomplish.
        options: What options or paths are available to you right now.

    Returns:
        A formatted plan that you can refer to when deciding your next action.
    """
    plan = (
        f"=== Agent Plan ===\n"
        f"SITUATION: {current_situation}\n"
        f"GOAL: {goal}\n"
    )
    if options:
        plan += f"OPTIONS: {options}\n"
    plan += "=================="
    return plan


@tool
def log_observation(observation: str, category: str = "general") -> str:
    """
    Log an observation to your scratchpad.

    Use this to record important findings as you navigate — things like
    'the careers page uses pagination', 'jobs are loaded dynamically',
    or 'found 3 relevant links'. These notes help you maintain context
    across many steps.

    Args:
        observation: What you observed or learned.
        category: Optional category tag (e.g., "navigation", "structure",
                  "data", "error").

    Returns:
        Confirmation that the observation was logged.
    """
    # In Phase 5 this will write to agent state; for now it's a pass-through
    # that the LLM can reference in its conversation history.
    return f"[{category.upper()}] Logged: {observation}"


# ── Tool Collection ───────────────────────────────────────────────────────────

UTILITY_TOOLS = [
    summarize_page,
    plan_next_steps,
    log_observation,
]
